### ISSUE TITLE
Post data contains HTML instead of Markdown

### ISSUE THREAD

**Issue by L1lle** [e1himself/mr-trevor-js#1]
Hi, Thanks a lot for this project. I am a fan of the multi columns addition and i really would like to use it in one of my projects.

But somehow the POST value contains the rendered HTML instead of plain Markdown when using `mr-trevor-js`. Switching back to `sir-trevor-js` it seems ok again.

Do I need to set an option?
![screen shot 2015-05-05 at 19 24 56](https://cloud.githubusercontent.com/assets/182834/7478681/91fbd8cc-f35c-11e4-937b-be068e128d88.png)

**Comment by e1himself** [comment]
Hi @L1lle! I'll check it out.

**Comment by e1himself** [comment]
I've checked the issue.
It looks like the original Sir Trevor works exactly the same now.

See this commit: [Removed convertToMarkdown](https://github.com/madebymany/sir-trevor-js/commit/fd4a0b8d977a2245f4a3e1281092bd85acfb94fc#diff-3)
Maybe SirTrevor team have some plan to refactor this somehow. For now saving to Markdown seems to be broken.

What can you do?
- Submit an issue to original Sir Trevor project 
- Fix it yourself and submit a Pull Request to original Sir Trevor project
- Stick with [Mr. Trevor 0.5.2](https://github.com/e1himself/mr-trevor-js-bower/releases/tag/0.5.2) which seems not to have this issue yet and wait until Sir Trevor team fix this

I'll merge those changes to Mr.Trevor as soon as the problem will be fixed.
Let me know if you submit an issue to original Sir Trevor project.

Cheers!

**Comment by L1lle** [comment]
Thank you for the reply. 

It really seems Sir-Trevor has moved away from Markdown and there is no turning back. It wouldn't have expect it. There is a good explanation about it in this issue https://github.com/madebymany/sir-trevor-js/issues/314 .
Well than. I will stick to your most recent version and will not render to Markdown and increase server security for post values. Or ran everything on server side through a HTML-to-Markdown-converter. Sounds inconvenient.
