### ISSUE TITLE
Differentiate from ST by making Columns a first-class feature.

### ISSUE THREAD

**Issue by hyrmedia** [e1himself/mr-trevor-js#3]
@e1himself I think the Sir Trevor project is excellent, but you've identified a **key missing feature** -- one that has been an obstacle to adoption of STjs for myself and [several](https://github.com/madebymany/sir-trevor-js/pull/177) - [others](https://github.com/madebymany/sir-trevor-js/pull/297).

But since the ST team has indicated they don't feel this approach matches their philosophy, I propose that you might proceed to maintain and promote Mr Trevor as a separate entity altogether. Were you to merge in 'sir-trevor-columns-block', I think it's a significant enough feature to differentiate the project from ST and warrant a proper split (_with appropriate attribution to the creators of Sir Trevor, of course, and fully respecting their copyright_).

Though, in that case, I might suggest a more distinctive name.. :)

**Comment by noolan** [comment]
:+1:

**Comment by e1himself** [comment]
Hi guys,

Sorry for being silent for a long time. Now I see that I don't have much time to spend on this project.
So I won't support it anymore. Sorry again.
